name: ansible-lint

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ansible-lint.yaml
      - "ansible/playbooks/*.yaml"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ansible-lint.yaml
      - "ansible/playbooks/*.yaml"

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run ansible-lint
        uses: ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c # v26.4.0
        with:
          args: ""
          requirements_file: "requirements.yaml"
